config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :galleries
  resources :types
  resources :specifications
  resources :motorcycles
  root to: 'static#home'
  get '/catalogo', to: 'static#catalogo'
  get '/detalle', to: 'static#detalle'
  get '/detalle2', to: 'static#detalle2'
  get '/financiacion', to: 'static#financiacion'
  get '/citas', to: 'static#citas'
  get '/contacto', to: 'static#contacto'
  get '/send_finan', to: 'forms#finan'
  get '/catal1', to: 'static#catal1'
  get '/catal2', to: 'static#catal2'

  post '/add_photo', to: 'images#add_photo'
end

app/models/specification.rb
class Specification < ApplicationRecord
  belongs_to :motorcycle
end

app/controllers/specifications_controller.rb
class SpecificationsController < ApplicationController
  before_action :set_specification, only: [:show, :edit, :update, :destroy]

  # GET /specifications
  # GET /specifications.json
  def index
    @specifications = Specification.all
  end

  # GET /specifications/1
  # GET /specifications/1.json
  def show
  end

  # GET /specifications/new
  def new
    @specification = Specification.new
  end

  # GET /specifications/1/edit
  def edit
  end

  # POST /specifications
  # POST /specifications.json
  def create
    @specification = Specification.new(specification_params)

    respond_to do |format|
      if @specification.save
        format.html { redirect_to @specification, notice: 'Specification was successfully created.' }
        format.json { render :show, status: :created, location: @specification }
      else
        format.html { render :new }
        format.json { render json: @specification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specifications/1
  # PATCH/PUT /specifications/1.json
  def update
    respond_to do |format|
      if @specification.update(specification_params)
        format.html { redirect_to @specification, notice: 'Specification was successfully updated.' }
        format.json { render :show, status: :ok, location: @specification }
      else
        format.html { render :edit }
        format.json { render json: @specification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specifications/1
  # DELETE /specifications/1.json
  def destroy
    @specification.destroy
    respond_to do |format|
      format.html { redirect_to specifications_url, notice: 'Specification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specification
      @specification = Specification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def specification_params
      params.require(:specification).permit(:name, :price)
    end
end

app/helpers/specifications_helper.rb
module SpecificationsHelper
end

app/views/specifications/_form.html.erb
<%= form_with(model: specification, local: true) do |form| %>
  <% if specification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(specification.errors.count, "error") %> prohibited this specification from being saved:</h2>

      <ul>
      <% specification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :specification_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :specification_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/specifications/edit.html.erb
<h1>Editing Specification</h1>

<%= render 'form', specification: @specification %>

<%= link_to 'Show', @specification %> |
<%= link_to 'Back', specifications_path %>

app/views/specifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Specifications</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @specifications.each do |specification| %>
      <tr>
        <td><%= specification.name %></td>
        <td><%= specification.price %></td>
        <td><%= link_to 'Show', specification %></td>
        <td><%= link_to 'Edit', edit_specification_path(specification) %></td>
        <td><%= link_to 'Destroy', specification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Specification', new_specification_path %>

app/views/specifications/new.html.erb
<h1>New Specification</h1>

<%= render 'form', specification: @specification %>

<%= link_to 'Back', specifications_path %>

app/views/specifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @specification.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @specification.price %>
</p>

<%= link_to 'Edit', edit_specification_path(@specification) %> |
<%= link_to 'Back', specifications_path %>