config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :galleries
  resources :types
  resources :specifications
  resources :motorcycles
  root to: 'static#home'
  get '/catalogo', to: 'static#catalogo'
  get '/detalle', to: 'static#detalle'
  get '/detalle2', to: 'static#detalle2'
  get '/financiacion', to: 'static#financiacion'
  get '/citas', to: 'static#citas'
  get '/contacto', to: 'static#contacto'
  get '/send_finan', to: 'forms#finan'
  get '/catal1', to: 'static#catal1'
  get '/catal2', to: 'static#catal2'

  post '/add_photo', to: 'images#add_photo'
end

app/models/motorcycle.rb
class Motorcycle < ApplicationRecord
  has_many :specifications
  has_many :types
  accepts_nested_attributes_for :specifications, allow_destroy: true
  accepts_nested_attributes_for :types, allow_destroy: true
end

app/controllers/motorcycles_controller.rb
class MotorcyclesController < ApplicationController
  before_action :set_motorcycle, only: [:show, :edit, :update, :destroy]

  # GET /motorcycles
  # GET /motorcycles.json
  def index
    @motorcycles = Motorcycle.all
  end

  # GET /motorcycles/1
  # GET /motorcycles/1.json
  def show
  end

  # GET /motorcycles/new
  def new
    @motorcycle = Motorcycle.new
  end

  # GET /motorcycles/1/edit
  def edit
  end

  # POST /motorcycles
  # POST /motorcycles.json
  def create
    @motorcycle = Motorcycle.new(motorcycle_params)

    respond_to do |format|
      if @motorcycle.save
        format.html { redirect_to @motorcycle, notice: 'Motorcycle was successfully created.' }
        format.json { render :show, status: :created, location: @motorcycle }
      else
        format.html { render :new }
        format.json { render json: @motorcycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motorcycles/1
  # PATCH/PUT /motorcycles/1.json
  def update
    respond_to do |format|
      if @motorcycle.update(motorcycle_params)
        format.html { redirect_to @motorcycle, notice: 'Motorcycle was successfully updated.' }
        format.json { render :show, status: :ok, location: @motorcycle }
      else
        format.html { render :edit }
        format.json { render json: @motorcycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motorcycles/1
  # DELETE /motorcycles/1.json
  def destroy
    @motorcycle.destroy
    respond_to do |format|
      format.html { redirect_to motorcycles_url, notice: 'Motorcycle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motorcycle
      @motorcycle = Motorcycle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def motorcycle_params
      params.require(:motorcycle).permit(:name, :price, 
                                    specifications_attributes: [:name, :price,
                                          :motorcycle_id, :id], 
                                    types_attributes: [:name, :price, 
                                          :motorcycle_id, :id, :_destroy, galleries_attributes: 
                                          [:type_id, :id, images_attributes: [:id, :gallery_id, :photo]]
                                    ]
                                    )
    end
end

app/helpers/motorcycles_helper.rb
module MotorcyclesHelper
end

app/views/motorcycles/_form.html.erb
<div class="motorcycle container">
  <%= form_with(model: motorcycle, local: true) do |form| %>
    <% if motorcycle.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(motorcycle.errors.count, "error") %> prohibited this motorcycle from being saved:</h2>

        <ul>
        <% motorcycle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :motorcycle_name %>
    </div>

    <div class="field">
      <%= form.label :price %>
      <%= form.number_field :price, id: :motorcycle_price %>
    </div>

    <!-- specs -->
    <div class="specs">
      <div class="items">
        <%= form.nested_fields_for :specifications do |f| %>
          <fieldset class="item">
            <%= f.label "especificaciónes" %>
            <%= f.text_area :name %>

            <%= f.label "valor" %>
            <%= f.text_field :price %>

            <a href="#" class="remove">remove</a>

            <%= f.hidden_field :id %>
            <%= f.hidden_field :_destroy %>
          </fieldset>
        <% end %>
      </div>
      <a href="#" class="btn btn-primary add-spec">Agregar especificación</a>
    </div>


    <div class="gallery">
      <!-- types -->
      <div class="items">
        <%= form.nested_fields_for :types do |t| %>
          <fieldset class="item">
            <%= t.label "Nombre Tipo" %>
            <%= t.text_area :name %>

            <%= t.label "valor tipo" %>
            <%= t.text_field :price %>

            <a href="#" class="remove">remove</a>

            <%= t.hidden_field :id %>
            <%= t.hidden_field :_destroy %>
          </fieldset>
          <% if t.object.gallery.nil? %>
            <%= t.fields_for :gallery, t.object.build_gallery do  |g| %>
              <div class="images-photo">
                <div class="items">
                  <%= g.nested_fields_for :images do |i| %>
                    <fieldset class="item">
                      <div class="modal-body">
                        <%= file_field_tag :photo %>
                      </div>
                    </fieldset>
                  <% end %>
                </div>
                <div class="text-center">
                  <a href="#" class="btn btn-primary image-spec">Agregar Imagen</a>
                </div>
              </div>
              
            <% end %>
          <% end %>
        <% end %>
      </div>
      <a href="#" class="btn btn-primary type-spec">Agregar tipo</a>
    </div>

    <br>
    <br>
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/motorcycles/_specifications.html.erb
<div class="items">
  <%= specs.nested_fields_for :specifications do |a| %>
    <fieldset class="item">
      <%= a.label "especificación" %>
      <%= a.text_area :name %>

      <%= a.label "precio" %>
      <%= a.text_field :price %>
      <a href="#" class="remove">remove</a>

      <%= form.hidden_field :id %>
      <%= form.hidden_field :_destroy %>
    </fieldset>
  <% end %>
  </div>
<a href="#" class="btn btn-primary">Agregar especificación</a>

app/views/motorcycles/edit.html.erb
<h1>Editing Motorcycle</h1>

<%= render 'form', motorcycle: @motorcycle %>

<%= link_to 'Show', @motorcycle %> |
<%= link_to 'Back', motorcycles_path %>

app/views/motorcycles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Motorcycles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @motorcycles.each do |motorcycle| %>
      <tr>
        <td><%= motorcycle.name %></td>
        <td><%= motorcycle.price %></td>
        <td><%= link_to 'Show', motorcycle %></td>
        <td><%= link_to 'Edit', edit_motorcycle_path(motorcycle) %></td>
        <td><%= link_to 'Destroy', motorcycle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Motorcycle', new_motorcycle_path %>

app/views/motorcycles/new.html.erb
<h1>New Motorcycle</h1>

<%= render 'form', motorcycle: @motorcycle %>

<%= link_to 'Back', motorcycles_path %>

app/views/motorcycles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @motorcycle.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @motorcycle.price %>
</p>

<p>
  <strong>SPECS:</strong>
  <textarea disabled>
    <%= @motorcycle.specifications.first.name %>
  </textarea>
</p>
<p>
  <strong>TYPE:</strong>
  <textarea disabled>
    <%= @motorcycle.types.first.name %>
  </textarea>
</p>

<%= link_to 'Edit', edit_motorcycle_path(@motorcycle) %> |
<%= link_to 'Back', motorcycles_path %>